Add a confirmation prompt to force a master branch when pushing directly to a github repo (ie: a repo that is not a fork)

diff --git a/bin/git_force_current b/bin/git_force_current
--- a/bin/git_force_current
+++ b/bin/git_force_current
@@ -1,5 +1,22 @@
 #!/bin/bash
 
-BRANCH=$(git branch | grep "^\*" | sed 's|^\* ||g')
+## gbc is part of the 'git_tools' package. Stands for 'git branch current', shows current branch
+
+if gbc | grep -q master; then
+  if ! (git remote -v | grep -q upstream); then
+    echo "Warning: Pushing to a master that is NOT A CLONE"
+    read -p "Type exactly 'yes' if you wish to proceed: " -n 3 -r
+    if [[ $REPLY = "yes" ]]; then
+      echo ""
+      echo "Okay, let's do this!"
+      echo ""
+    else
+      echo "Aborting"
+      exit -1
+    fi
+  fi
+fi
+
+BRANCH=$(gbc | sed 's|^\* ||g')
 echo "FORCE Pushing Branch: $BRANCH"
 git push origin -f $BRANCH
