Add "mv_file_to_branch"

diff --git a/mv_file_to_branch b/mv_file_to_branch
--- a/mv_file_to_branch
+++ b/mv_file_to_branch
@@ -1,7 +1,9 @@
 #!/bin/bash
 
-FILE_TO_MOVE="$1"
-BRANCH="$2"
+BRANCH=$1
+shift
+echo $@
+echo $#
 
 set -eux
 
@@ -10,17 +12,29 @@ function usage() {
   exit 1
 }
 
-if [ ! -e "$FILE_TO_MOVE" ]; then
-  echo "File does not exist: $FILE_TO_MOVE"
+
+if [ "$#" = 0 ]; then
+  usage
   exit 1
 fi
 
 
-TARGET_FOLDER=$(dirname $FILE_TO_MOVE)
-FILE_NAME=$(basename $FILE_TO_MOVE)
+TEMP_FOLDER=$(mktemp -d)
+#trap "rm -rf $TEMP_FOLDER" EXIT
 
-cp $FILE_TO_MOVE ~/$FILE_NAME
+for i in "$@"; do
+  if [ ! -f "$i" ]; then
+    echo "Error, not a file: $i"
+  fi
+done
+
+cp $@ $TEMP_FOLDER/
 git checkout "$BRANCH"
-mkdir -p $TARGET_FOLDER
-mv ~/$FILE_NAME "$FILE_TO_MOVE"
+
+for i in "$@"; do
+  TARGET_FOLDER=$(dirname "$i")
+  FILE_NAME=$(basename "$i")
+  mkdir -p "$TARGET_FOLDER"
+  mv "$TEMP_FOLDER/$FILE_NAME" "$TARGET_FOLDER/$FILE_NAME"
+done
 
